### ISSUE TITLE
Crash with MineFactoryReloaded

### ISSUE THREAD

**Issue by Adaptivity** [kingrunes/Somnia#11]
http://pastebin.com/V7dGvZFn occurs randomly in the world when MFR generating it's trees. skyboy said it should be fixed on Somnia side.

**Comment by kingrunes** [comment]
Have you tested without Somnia installed?

**Comment by Adaptivity** [comment]
Without Somnia everything fine.

**Comment by Adaptivity** [comment]
I'm having some feelings that it is not Somnia fault. I'll retest it with new version soon (probably today), I have no clue why Somnia mentioned in the log but it seems that Nature Overhaul wrongly interact with non-vanilla (mod) leaves.
