### ISSUE TITLE
Somnia-1.4.2.27 Potion effect issues

### ISSUE THREAD

**Issue by walkerjonny** [kingrunes/Somnia#17]
Hi,
There are some troubles with Potion effects that start combined at world loading (repeatable) and sporadic without any visible reason while playing (then only one potion effect at a time). Also there is one Potion - Slowness IV - that starts at a given time and then stays within a circle for infinite time. The circle starts at 7 seconds, counts down to 2 seconds and starts over beginning at 7 seconds again. The command "/effect <username> clear" kills this just for a few seconds until the circle starts over at 7 seconds again. This Potion effect stays then at world saving and world loading until I remove Somnia from my mods.
Especially the Slowness Potion issue is very annoying. 
Unfortunately there is nothing helpful within the log files - no error pointing to this and no message about this.

**Comment by kingrunes** [comment]
The repeated slowness was intentional, if you are extremely fatigued in real life moving around would be more difficult. However, the effect spam isn't intentional, it'll be down to the fact I didn't make the current potion stage persist with world saves.

Shouldn't be difficult to fix :)

**Comment by kingrunes** [comment]
Fixed in latest commit, build no. 29.
