### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Nianor** [kingrunes/Somnia#18]
Every time I launch, I get this crash:
https://paste.ee/p/9nDA7
I use MultiMC, and previously, my minecraft was pretty unstable, and I would get a crash like this about once every fifteen minutes, but I updated a mod and got Somnia, and now it crashes every time I try to launch. Could someone help me find the root of the problem?

**Comment by yut23** [comment]
It looks like something to do with audio (OpenAL32.dll). Make sure you've run Windows Update and installed any Intel driver updates.
Additionally, your computer is 64-bit, but you are running 32-bit Java, so try installing the latest 64-bit version of Java 7 and see if that helps. You can set which Java runtime MultiMC uses in the Java section of the settings.
