### ISSUE TITLE
Crash, don't know what the issue is

### ISSUE THREAD

**Issue by WolfieWaffle** [kingrunes/Somnia#20]
http://pastebin.com/n7nd3cGw

**Comment by kingrunes** [comment]
You're running #23 which is the only version affected by this bug. You can download the latest 1.7.10 build from here http://codeheist.net:8080/job/Somnia/32/

**Comment by WolfieWaffle** [comment]
What are the chances I get the ONE broken build... -_- Anyways, I thanks!
