### ISSUE TITLE
compatibility of somnia with chicken chunkload

### ISSUE THREAD

**Issue by Bellwar** [kingrunes/Somnia#23]
If you know about this bug then sorry for postting but didnt find it on the site.

At least i think its between this two mods. Im not to much in modding so maybe its some stupid bug i didnt configurate. Here is the crashlog: http://pastebin.com/b1ij4NL3

I think you have versions of all the mods in the pastebin and if you need any more info i will try help. :)

**Comment by kingrunes** [comment]
This was already patched for 1.8 versions but I haven't released a hotfix for 1.7.10 yet. I'll get on that now.

**Comment by kingrunes** [comment]
I've released a patch on the forum thread for 1.7.10
