### ISSUE TITLE
Suffocating While Sleeping Prevents Respawning

### ISSUE THREAD

**Issue by UndeadZeratul** [kingrunes/Somnia#27]
Description
=
Sleeping in a bed that would cause suffocation damage (Which is a known vanilla bug) causes the sleep GUI to get stuck on top of the overlay screen, yet not respond to any interaction from the player.

Versions
=
__Minecraft:__ 1.7.10
__Forge:__ 10.13.4.1448
__Somnia:__ 1.4.3.1

Recreate
=
Sleep in a bed that would cause suffocation damage.  When you eventually die, try to get out of bed.  The GUI screen no longer responds to the player clicking the button, and the only way to continue is to close the game and re-open.

Known Workaround
=
When the GUI becomes unresponsive, it is possible to press the Escape key to force close the GUI, and then click the respawn button.  This was only possible while the progress bar and clock were still on the screen.  If I let them finish and go away, the "Get out of Bed" button stayed on the screen, unable to be clicked, nor could I press Escape to close the GUI.

**Comment by callumerrington** [comment]
I did implement a feature a while ago which automatically wakes the player upon taking damage, but I guess over time it broke and I didn't notice. Anyway, should be fixed as of build 54.

Thanks for reporting this :)
